%Reading the DeBaCl tree file generated by the python code.
function DBLoutput=ReadDeBaCltreeOutputFile(treeoutputFileAddress)

    A=importdata(treeoutputFileAddress);
    
    DBLoutput{size(A,1)-4,8} = [];
    for i=4:(size(A,1)-1)
        Str=A{i};
        Str(strfind(Str, '=')) = [];
        Key   = '|'; 
        Index = strfind(Str, Key);
        for j=1:(size(Index,2)-2)
            Value = sscanf(Str(Index(j) + length(Key):end), '%g', 1);
            DBLoutput{i-3,j}=Value;
        end
        NewStr=Str(Index(8):end);
        DBLoutput{i-3,8}=str2double(regexp(NewStr,'\d*','Match'));
    end

end